url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Troy Demers
email: troydemers@gmail.com
description: "Young New Jersey-based poet, copywriter, musician, photographer, existentialist, content creator and consumer."

# Team names, titles and social links
people:
- name: Troy Demers
  pic: 1
  position: Personal Brand Director
  social:
    - title: twitter
      url: #https://twitter.com/troykdemers
    - title: facebook
      url: #https://www.facebook.com/TheRealTroyCool
    - title: linkedin
      url: #https://www.linkedin.com/in/troydemers/
    - title: instagram
      url: #https://www.instagram.com/troycapybara/

# Build settings
markdown: kramdown
permalink: pretty
theme: tactile
